version: '3.8'

services:
  database:
    image: postgres:15
    container_name: sakila-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pwd
      POSTGRES_DB: sakila
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sakila/postgres-sakila-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./culturelive
      dockerfile: Dockerfile
    container_name: culturelive-api
    ports:
      - '3000:3000'
    volumes:
      - ./culturelive/src:/app/src
    depends_on:
      - database
    restart: always

volumes:
  postgres-data:
